Description: >
    This template deploys an Application Load Balancer that exposes ECS services.
    It is created in a separate nested template, so it can be referenced by all of the other nested templates.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    EnvironmentTag:
        Description: Value for the Environment tag in created resources
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Applicaion Load Balancer should be deployed to

    Subnets:
        Description: Choose which subnets the Applicaion Load Balancer should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroups:
        Description: Select the Security Groups to apply to the Applicaion Load Balancer
        Type: List<AWS::EC2::SecurityGroup::Id>

    CertificateArn:
        Description: The ARN of aws certificate that will be used in LoadBalancer
        Type: String

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref EnvironmentName
            Subnets: !Ref Subnets
            SecurityGroups: !Ref SecurityGroups
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
                - Key: Environment
                  Value: !Ref EnvironmentTag

    HttpLoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP
            TargetGroupAttributes:
              - Key: deregistration_delay.timeout_seconds
                Value: 60
              - Key: stickiness.enabled
                Value: true
              - Key: stickiness.type
                Value: lb_cookie
              - Key: stickiness.lb_cookie.duration_seconds
                Value: 300
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup

    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${AWS::StackName}-def
            VpcId: !Ref VPC
            Port: 80
            Protocol: HTTP

Outputs:

    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value: !Ref LoadBalancer

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName

    HttpsListener:
        Description: A reference to a port 443 listener
        Value: !Ref HttpsLoadBalancerListener

    TargetGroupARN:
        Description: The ARN of the target group
        Value: !Ref DefaultTargetGroup
